export const THEMES = {
  indigo: {
    id: 'indigo',
    name: 'Indigo',
    swatch: '#6366f1',
    colors: {
      primary: '#6366f1',
      primaryDark: '#4f46e5',
      primaryLight: '#818cf8',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
      bg: '#f8fafc',
      surface: '#ffffff',
      text: '#1e293b',
      textMuted: '#64748b',
      border: '#e2e8f0',
    },
  },
  emerald: {
    id: 'emerald',
    name: 'Emerald',
    swatch: '#10b981',
    colors: {
      primary: '#10b981',
      primaryDark: '#059669',
      primaryLight: '#34d399',
      success: '#22c55e',
      warning: '#f59e0b',
      danger: '#ef4444',
      bg: '#f0fdf4',
      surface: '#ffffff',
      text: '#14532d',
      textMuted: '#64748b',
      border: '#bbf7d0',
    },
  },
  rose: {
    id: 'rose',
    name: 'Rose',
    swatch: '#f43f5e',
    colors: {
      primary: '#f43f5e',
      primaryDark: '#e11d48',
      primaryLight: '#fb7185',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#dc2626',
      bg: '#fff1f2',
      surface: '#ffffff',
      text: '#881337',
      textMuted: '#64748b',
      border: '#fecdd3',
    },
  },
  amber: {
    id: 'amber',
    name: 'Amber',
    swatch: '#f59e0b',
    colors: {
      primary: '#f59e0b',
      primaryDark: '#d97706',
      primaryLight: '#fbbf24',
      success: '#10b981',
      warning: '#ea580c',
      danger: '#ef4444',
      bg: '#fffbeb',
      surface: '#ffffff',
      text: '#78350f',
      textMuted: '#64748b',
      border: '#fde68a',
    },
  },
  violet: {
    id: 'violet',
    name: 'Violet',
    swatch: '#8b5cf6',
    colors: {
      primary: '#8b5cf6',
      primaryDark: '#7c3aed',
      primaryLight: '#a78bfa',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
      bg: '#f5f3ff',
      surface: '#ffffff',
      text: '#4c1d95',
      textMuted: '#64748b',
      border: '#ddd6fe',
    },
  },
  ocean: {
    id: 'ocean',
    name: 'Ocean',
    swatch: '#0ea5e9',
    colors: {
      primary: '#0ea5e9',
      primaryDark: '#0284c7',
      primaryLight: '#38bdf8',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
      bg: '#f0f9ff',
      surface: '#ffffff',
      text: '#0c4a6e',
      textMuted: '#64748b',
      border: '#bae6fd',
    },
  },
};

export const DEFAULT_THEME_ID = 'indigo';

export const THEME_LIST = Object.values(THEMES);

export const getThemeById = (themeId) => THEMES[themeId] || THEMES[DEFAULT_THEME_ID];
